name: Dump
description: |
  環境変数とgithubコンテキストをログに出力します。
  ワークフローのデバックの検証です。
inputs: 
  enable-context:
    default: 'true'
    required: false
    description: コンテキストを出力するか

outputs:
  demped-date:
    value: ${{ steps.current.outputs.date }}
    description: ダンプ日時

runs:
  using: composite
  steps:
    - run: printenv | sort
      shelll: bash
    - run: echo "S{ CONTEXT }"
      if: ${{ inputs.enable-context =='true' }}
      env:
        CONTEXT: ${{ toJSON(github) }}
      shell: bash
    - id: current
      run: echo "date=$(date)" >> "${GTIHUB_OUTPUT}"
      shell: bash