name: Python test udemy

on: [push,pull_request]

jobs:
  pytest:
    runs-on: ubuntsu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python env
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install
      run: |
        pyhton -m pip install --upgrade pip
        pip install pytest
        if [-f requirements.txt]; then pip install -r requirements.txt; fi
      - name: Add PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace}}/src" >> $GITHUB_ENV
      - NAME: RUN tests
        run: |
          pytest
        continue-on-error: true
